-- Campus Equipment Checkout System
-- Synthetic instructor demo schema for PostgreSQL / Supabase.

create table if not exists public.equipment_categories (
  id bigint generated by default as identity primary key,
  category_code text not null unique,
  category_name text not null,
  notes text
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  asset_code text not null unique,
  equipment_name text not null,
  category_id bigint not null references public.equipment_categories(id) on update cascade on delete restrict,
  brand text,
  model text,
  condition_status text not null check (condition_status in ('Good','Needs maintenance','Damaged')),
  availability_status text not null default 'Available' check (availability_status in ('Available','Checked out','Maintenance','Retired')),
  purchase_year integer check (purchase_year between 1990 and 2100),
  created_at timestamptz not null default now()
);

create table if not exists public.borrowers (
  id bigint generated by default as identity primary key,
  borrower_code text not null unique,
  full_name text not null,
  department text not null,
  email text unique,
  borrower_type text not null check (borrower_type in ('Student','Staff','Lecturer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.checkouts (
  id bigint generated by default as identity primary key,
  checkout_code text not null unique,
  equipment_id bigint not null references public.equipment(id) on update cascade on delete restrict,
  borrower_id bigint not null references public.borrowers(id) on update cascade on delete restrict,
  checkout_date date not null,
  due_date date not null,
  returned_date date,
  checkout_condition text not null check (checkout_condition in ('Good','Needs maintenance','Damaged')),
  return_condition text check (return_condition in ('Good','Needs maintenance','Damaged')),
  status text not null check (status in ('Borrowed','Returned','Overdue')),
  notes text,
  created_at timestamptz not null default now(),
  check (due_date >= checkout_date),
  check (returned_date is null or returned_date >= checkout_date)
);

create index if not exists idx_equipment_category on public.equipment(category_id);
create index if not exists idx_checkouts_equipment on public.checkouts(equipment_id);
create index if not exists idx_checkouts_borrower on public.checkouts(borrower_id);
create index if not exists idx_checkouts_due_status on public.checkouts(status, due_date);

alter table public.equipment_categories enable row level security;
alter table public.equipment enable row level security;
alter table public.borrowers enable row level security;
alter table public.checkouts enable row level security;
-- No access policies are included in this baseline. Browser access is denied until policies are added.
